In [6]:
from sklearn import datasets,metrics
from sklearn.metrics import confusion_matrix
from sklearn.cluster import AffinityPropagation
import numpy as np

In [7]:
X, y  = datasets.load_digits(return_X_y = True)
n_samples, n_features = x.shape
X.shape
output = y

clus = AffinityPropagation(preference = -45000, damping = .9, max_iter=1000)
clus.fit_predict(x)
out = clus.labels_

In [15]:
cluster = [[0 for x in range(out.shape[0])] for y in range(12)]
cluster = np.array(cluster)
for i in range(out.shape[0]):
    k=0
    for j in range(out.shape[0]):
        if out[i] == out[j]:
            cluster[out[i]][k] = output[j]
            k = k+1
        else:
            cluster[out[i]][k] = -1
            k = k+1
          
count = [[0 for x in range(cluster.shape[0])] for y in range(cluster.shape[0])]
for i in range(cluster.shape[0]):
    for j in range(cluster.shape[1]):
        if cluster[i][j] != -1:
            count[i][cluster[i][j]] = count[i][cluster[i][j]] + 1
Labels_new=[]
for i in range(cluster.shape[0]):
    Labels_new.append(count[i].index(max(count[i])))
    
print(Labels_new)
labels = []
for i in range(out.shape[0]):
    labels.append(Labels_new[out[i]])

[1, 3, 6, 0, 5, 7, 5, 8, 4, 2, 9, 0]


In [18]:
scores = metrics.fowlkes_mallows_score(output, labels)
print("Fowlkes Mallows score is ",scores)
confusion_Matrix = metrics.confusion_matrix(output, labels)
confusion_Matrix[:,9] = [-1 for i in range(10)]
print(confusion_Matrix)

Fowlkes Mallows score is  0.6870045489739688
[[175   0   0   0   2   0   1   0   0  -1]
 [  0  55  24   2   0   1   1   0  99  -1]
 [  2   1 136   3   0   0   0   3  24  -1]
 [  1   0   0 147   0   2   0  10   7  -1]
 [  0   4   0   0 161   1   0   7   8  -1]
 [  2   0   0   0   1 159   1   0   1  -1]
 [  1   0   0   0   1   1 174   0   3  -1]
 [  0   0   0   0   3   1   0 168   7  -1]
 [  2   6   4  21   0   8   0   1 127  -1]
 [  8  17   0  12   0   7   0   6   2  -1]]
