In [5]:
from sklearn import datasets,metrics
from sklearn.metrics import confusion_matrix
from sklearn.cluster import AgglomerativeClustering
import numpy as np

In [6]:
X, y  = datasets.load_digits(return_X_y = True)
n_samples, n_features = X.shape
X.shape
output = y

clus = AgglomerativeClustering(linkage="ward", n_clusters=10)
clus.fit_predict(X)
out = clus.labels_

In [8]:
cluster = [[0 for x in range(out.shape[0])] for y in range(10)]
cluster = np.array(cluster)
for i in range(out.shape[0]):
    k=0
    for j in range(out.shape[0]):
        if out[i] == out[j]:
            cluster[out[i]][k] = output[j]
            k = k+1
        else:
            cluster[out[i]][k] = -1
            k = k+1
          
count = [[0 for x in range(cluster.shape[0])] for y in range(cluster.shape[0])]
for i in range(cluster.shape[0]):
    for j in range(cluster.shape[1]):
        if cluster[i][j] != -1:
            count[i][cluster[i][j]] = count[i][cluster[i][j]] + 1
Labels_new=[]
for i in range(cluster.shape[0]):
    Labels_new.append(count[i].index(max(count[i])))
    
print(Labels_new)
labels = []
for i in range(out.shape[0]):
    labels.append(Labels_new[out[i]])

[5, 3, 2, 7, 8, 4, 6, 0, 1, 1]


In [10]:
scores = metrics.fowlkes_mallows_score(output, labels)
print("Fowlkes Mallows score is ",scores)
confusion_Matrix = metrics.confusion_matrix(output, labels)
confusion_Matrix[:,9] = [-1 for i in range(10)]
print(confusion_Matrix)

Fowlkes Mallows score is  0.8321395046705492
[[178   0   0   0   0   0   0   0   0  -1]
 [  0 155  27   0   0   0   0   0   0  -1]
 [  0   0 166   0   0   0   0   1  10  -1]
 [  0   0   0 169   0   0   0   1  13  -1]
 [  0   0   0   0 178   0   0   3   0  -1]
 [  0   0   0   2   0 179   1   0   0  -1]
 [  0   0   0   0   0   0 180   0   1  -1]
 [  0   0   0   0   0   0   0 179   0  -1]
 [  0   3   4   1   0   0   0   1 165  -1]
 [  0  20   0 145   0   2   0  11   2  -1]]
